studentid=input("Enter value for studentId:")
studentname=input("Enter value for studentname:")
marks1=input("Enter value for marks1:")
marks2=input("Enter value for marks2:")
marks3=input("Enter value for marks3:")
totalmarks=int(marks1)+int(marks2)+int(marks3)
print("Student ID is ",studentid)
print("Student name is ",studentname)
print("Student got marks1 is ",marks1)
print("Student got marks2 is ",marks2)
print("Student got marks3 is ",marks3)
print("Studnet got total marks as ",totalmarks)